### PR TITLE
HT-2614 create fixtures in rights_current

### PR DESCRIPTION
**Pull request by moseshll**

### CODE REVIEW

**Comment by moseshll** [comment]
This is the same fixture as on the Jira ticket, except any person-linked user has been replaced with 'libadm'
The new t/rights.t test will be extended when I commit HT-2615.

**Review by aelkiss — COMMENTED** [review]
I think this is a good starting place; I'm not wholly convinced we need the opaque IDs there, and we might be better served by using object IDs in the fixtures like `test.pd_bib_umich_open` (e.g. just concatenate the reason/attribute/source/access profile).

**Comment by moseshll** [comment]
The note text had some potentially personally identifying values so I NULLed that out in addition to turning all users into libadm. So these are all attested (attr,reason,src,profile) combinations but rows will no longer match any particular row in rights_current in any of the other details.

**Review by aelkiss — APPROVED** [review]
Let's go ahead and merge this, but be mindful of how we use it in tests such that we aren't throwing lots of opaque identifiers / magic numbers in the tests and asserting behavior about them without some further explanation.

**Pull request merged**
