### PR TITLE
Dev 932 smush together title author

### PR DESCRIPTION
**Pull request by liseli**

### CODE REVIEW

**Comment by mwarin** [comment]
I've been added as a reviewer, but I don't think this is ready? At commit [e925924](https://github.com/hathitrust/mdp-lib/pull/29/commits/e925924528bd1043124a69f4a78fded8e52f27d0)

**Comment by liseli** [comment]
This PR change the function `get_title`. Right now, the title is extracted from Solr index (`title_display` field), instead of generating it concatenating fields from MARC field. This change was tested locally and in [beta-1.babel.hathitrust.org](http://beta-1.babel.hathitrust.org/) 
image

**Review by aelkiss — APPROVED** [review]
I don't understand why this whole module uses regular expressions to parse the solr result, but the functionality to get the display title at least looks in line with the other functionality here. It could all probably be simplified significantly if we got json from solr instead of XML, but I wouldn't want to do that without having tests first... Something to keep in mind as an opportunity for refactoring @moseshll @liseli

**Comment by aelkiss** [comment]
I would also suggest squashing before merging

**Comment by liseli** [comment]
> I don't understand why this whole module uses regular expressions to parse the solr result, but the functionality to get the display title at least looks in line with the other functionality here. It could all probably be simplified significantly if we got json from solr instead of XML, but I wouldn't want to do that without having tests first... Something to keep in mind as an opportunity for refactoring @moseshll @liseli

This module uses regular expression because the Solr output is in XML format (It is a decision that complicate the logic, but there is not any special reason). Martin and I have a discussion about refactoring this code, but we decided only to change the part related with title_display.

**Pull request merged**
